### PR TITLE
Open page (background content) shouldn't be scrollable when mobile nav is open

### PR DESCRIPTION
**Pull request by asavin**
Fix for https://github.com/redbadger/website-honestly/issues/326

### CODE REVIEW

**Comment by dstodolny** [comment]
@grahammendick have a clevaaah fix for that

**Comment by grahammendick** [comment]
I tried the fix from http://luxiyalu.com/playground/overlay/
```
html, body {
  height: 100%;
}
```
Bu it didn't seem to work on iOS.

Whatever we go with, I think the 'same' fix should be used on blog and website-honestly (see https://github.com/redbadger/website-honestly/issues/171).

**Comment by samsmith1983** [comment]
This seems to be working on desktop Chrome, but not on mobile devices.

Also, I can break it on desktop Chome by:

- Go to blog page
- Resize window to mobile size
- Open nav menu
- Click a link on the menu
- Click 'back'

Now background is scrollable.

**Comment by samsmith1983** [comment]
^ @asavin @dstodolny @grahammendick

**Comment by samsmith1983** [comment]
This is now working nicely. The background still becomes scrollable after hitting the 'back' button (see comment above) - however I don't see this as a blocking issue.

**Pull request merged**
