### PR TITLE
UX Testing Jobs Link In Header

### PR DESCRIPTION
**Pull request by callerc1**
Add Jobs link to header

### CODE REVIEW

**Comment by chris-brookes** [comment]
@callerc1 - For some reason git hub hasn't picked up that the master has been updated and this PR isn't in sync with it. Can you sort this out please? (it's only a tiny change that went through #84 )

**Comment by callerc1** [comment]
@chris-brookes all good now?

**Comment by chris-brookes** [comment]
@callerc1 - No, the #84 change isn't in your code, and I want to make sure your PR doesn't overwrite his change.

**Comment by callerc1** [comment]
@chris-brookes Ok should be there now.

**Pull request merged**
