### PR TITLE
Link color on hover and a nice transition

### PR DESCRIPTION
**Pull request by asavin**
Bringing inline link styles up to date with the branding http://brand.red-badger.com/d/WEl30uS4YzKw/red-badger-styleguide-style-guide#/elements/links

### CODE REVIEW

**Comment by gregdorward** [comment]
Looks good to me - tested across multiple browsers (IE, Chrome, Firefox, Safari). Happy for it to be merged in if @chris-brookes is also ok with it?

**Comment by chris-brookes** [comment]
@asavin - The links on the blog list page do not have the new style. Should they not have the same style to match the blog story page? eg. .../blog/?category=Badger+Life

screen shot 2017-02-13 at 10 56 41

**Comment by asavin** [comment]
@chris-brookes yeah good catch - we're asking people not to create any links in the blog brief anymore, but might be a good idea to fix this for the legacy posts.

**Comment by asavin** [comment]
@chris-brookes fixed now

**Comment by chris-brookes** [comment]
Yep, looks good now.

**Pull request merged**
