### PR TITLE
Fix button hover state

### PR DESCRIPTION
**Pull request by Etiene**
Fixes issue [#378](https://github.com/redbadger/website-honestly/issues/378), part of PR [#389](https://github.com/redbadger/website-honestly/pull/389)

### CODE REVIEW

**Comment by chris-brookes** [comment]
@Etiene Also the 'Show more' button on the blog search results page.
screen shot 2017-02-28 at 15 03 03

**Comment by dstodolny** [comment]
Buttons should be fixed however hover state on button in search results cannot be tested before merging it because search result page doesn't work locally. ☠️

**Comment by chris-brookes** [comment]
@dstodolny - The 'All' category button does not show the hover over style.

**Comment by chris-brookes** [comment]
The hover-over style is missing from the Previous button. Can you add the reverse style of white text on black background.

screen shot 2017-03-06 at 14 35 16

**Pull request merged**
